### Get all directors
GET http://localhost:9080/MovieTradingPlatform/api/directors

### Get director
GET http://localhost:9080/MovieTradingPlatform/api/directors/4c54ab20-b701-4dc8-b7d2-f99f8c0a9d45

### Create new director
POST http://localhost:9080/MovieTradingPlatform/api/directors
Content-Type: application/json

{
  "name": "Quentin Tarantino",
  "description": "Crazy basterd"
}

### Create new director
POST http://localhost:9080/MovieTradingPlatform/api/directors
Content-Type: application/json

{
  "name": "Dennis Villeneuve",
  "description": "Sci-fi master"
}

### Create new director
POST http://localhost:9080/MovieTradingPlatform/api/directors
Content-Type: application/json

{
  "name": "Sean Baker",
  "description": "Indie king!"
}

### Update director
PUT http://localhost:9080/MovieTradingPlatform/api/directors/4ec5f341-d0fa-4e51-bf01-a6e773ca814e
Content-Type: application/json

{
  "name": "Quentin Jerome Tarantino"
}

### Delete director
DELETE http://localhost:9080/MovieTradingPlatform/api/directors/4ec5f341-d0fa-4e51-bf01-a6e773ca814e


### Get all movies for a director
GET http://localhost:9080/MovieTradingPlatform/api/directors/afeb89ed-782d-4ceb-a13f-becb3e54742c/movies

### Get specific movie for a director
GET http://localhost:9080/MovieTradingPlatform/api/directors/afeb89ed-782d-4ceb-a13f-becb3e54742c/movies/905807bf-1a5f-40db-b557-03be5c2e7c98

### Add movie to director
POST http://localhost:9080/MovieTradingPlatform/api/directors/afeb89ed-782d-4ceb-a13f-becb3e54742c/movies
Content-Type: application/json

{
  "title": "Anora",
  "releaseDate": "2024-11-01",
  "genres": ["DRAMA"]
}

### Update movie
PUT http://localhost:9080/MovieTradingPlatform/api/directors/afeb89ed-782d-4ceb-a13f-becb3e54742c/movies/c72ff878-eacc-4251-8673-1f09603a2e64
Content-Type: application/json

{
  "releaseDate": "1999-12-15",
  "genres": ["COMEDY", "ACTION"]
}

### Remove movie
DELETE http://localhost:9080/MovieTradingPlatform/api/directors/4c54ab20-b701-4dc8-b7d2-f99f8c0a9d45/movies/905807bf-1a5f-40db-b557-03be5c2e7c98
