### Get all directors
GET http://localhost:9080/MovieTradingPlatform/api/directors

### Get director
GET http://localhost:9080/MovieTradingPlatform/api/directors/1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4e5b6b

### Create new director
POST http://localhost:9080/MovieTradingPlatform/api/directors
Content-Type: application/json

{
  "name": "Quentin Tarantino"
}

### Update director
PUT http://localhost:9080/MovieTradingPlatform/api/directors/d05d382a-22f0-4cee-b029-d6f93002d914
Content-Type: application/json

{
  "name": "Quentin Jerome Tarantino"
}

### Delete director
DELETE http://localhost:9080/MovieTradingPlatform/api/directors/d05d382a-22f0-4cee-b029-d6f93002d914

### Add movie to director
POST http://localhost:9080/MovieTradingPlatform/api/directors/1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4e5b6b/movies
Content-Type: application/json

{
  "title": "Anora",
  "releaseDate": "2024-11-01",
  "genres": ["DRAMA"]
}

### Update movie
PUT http://localhost:9080/MovieTradingPlatform/api/directors/1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4e5b6b/movies/385503c5-3266-4d2d-b107-4d569de4ef9e
Content-Type: application/json

{
  "releaseDate": "1999-12-15",
  "genres": ["COMEDY", "ACTION"]
}

### Remove movie
DELETE http://localhost:9080/MovieTradingPlatform/api/directors/1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4e5b6b/movies/385503c5-3266-4d2d-b107-4d569de4ef9e